### ISSUE TITLE
Job Runner: wrong usage of dbfilter in get_db_names

### ISSUE THREAD

**Issue by yelizariev** [OCA/connector#128] opened 2015-10-13 13:11 UTC
job runner is not activated in case of using %d or %h in db_filter

```
def get_db_names(self):
    if openerp.tools.config['db_name']:
        db_names = openerp.tools.config['db_name'].split(',')
    else:
        db_names = openerp.service.db.exp_list()
    dbfilter = openerp.tools.config['dbfilter']
    if dbfilter:
        db_names = [d for d in db_names if re.match(dbfilter, d)]
    _logger.info('************************ get_db_names %s', [openerp.tools.config['db_name'], openerp.service.db.exp_list(), dbfilter])
    return db_names
```

log output:

```
2015-10-13 12:57:54,990 25521 INFO ? openerp.addons.connector.jobrunner.runner: ************************ get_db_names [False, [u'erp'], '^%d$']
```

**Comment by sbidoul** [comment] 2015-10-13 13:18
It's a duplicate of #58. If you don't mind I'll close this one. Do not hesistate to reopen if needed.

**Closed as completed by sbidoul** 2015-10-13 13:18 UTC
